# render.yaml - Static site (Create React App / Vite)
previews:
  generation: automatic

services:
  - type: web
    name: my-react-app                 # change to your service name
    runtime: static
    repo: https://github.com/your-org/your-repo  # optional, defaults to repo containing this file
    branch: main                       # change if needed
    buildCommand: npm install && npm run build  # or: yarn && yarn build
    staticPublishPath: ./build         # CRA -> ./build ; Vite -> ./dist
    plan: free
    previews:
      generation: automatic
    buildFilter:
      paths:
        - src/**/*.js
        - package.json
      ignoredPaths:
        - src/**/*.test.js
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    routes:
      - type: rewrite
        source: /app/*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://api.example.com
